<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>OsEngine.OrderFlowResearch.Tests</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\OsEngine\OsEngine.csproj" />
    <EmbeddedResource Include="..\..\OsEngine\App.xaml" LogicalName="Research.App.xaml" />
    <EmbeddedResource Include="..\..\OsEngine\OsData\OrderFlow\OrderFlowResearchUi.xaml" LogicalName="Research.Ui.xaml" />
  </ItemGroup>

</Project>
